In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
# path_to_text = '/content/drive/MyDrive/datasets-spam.csv'
#path_to_text = 'datasets-spam.csv'
path_to_text = 'books_and_authors'
data = pd.read_csv(path_to_text, names=['v1', 'v2'])

# Creating the feature set and label set
label = data['v1']
text = data['v2']

text

0      Pretty soon I wanted to smoke, and asked the w...
1      Her sister, Miss Watson, a tolerable slim old ...
2      Now she had got a start, and she went on and t...
3      Miss Watson she kept pecking at me, and it got...
4      I set down again, a-shaking all over, and got ...
                             ...                        
994    I was on the point of asking him what that wor...
995      1. Knowledge of Literature.--Nil.\r\n  2.   ...
996    I see that I have alluded above to his powers ...
997    During the first week or so we had no callers,...
998    It was upon the 4th of March, as I have good r...
Name: v2, Length: 999, dtype: object

# New Section

### Прво целосно прочистен

In [5]:
import nltk

nltk.download('omw-1.4')
nltk.download('punkt')

from nltk.corpus import stopwords, wordnet

nltk.download('stopwords')
stopwords_ = stopwords.words('english')

nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer

wnl = WordNetLemmatizer()

nltk.download('averaged_perceptron_tagger')

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN
import string

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Unzipping corpora/omw-1.4.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


In [6]:
text_preprocessed = []
for sentence in text:
    #sentence lower
    sentence = sentence.lower()

    #string punct
    sentence = sentence.translate(str.maketrans('', '', string.punctuation))
    #tokenize
    tokens = nltk.word_tokenize(sentence)
    
    # stop-words
    tokens_stop_words = []
    
    for token in tokens:
          if token not in stopwords_:
                tokens_stop_words.append(token)
                
    # Lemmatization
    tokens_lemma = []
    for token in tokens_stop_words:
          tokens_lemma.append(wnl.lemmatize(token, get_wordnet_pos(nltk.pos_tag([token])[0][1])))
            
    final = ' '.join(tokens_lemma)
    
    text_preprocessed.append(final)

Без процесирање, само мали букви и токенизација.

In [7]:
text_preprocessed_1 = []
for sentence in text:
    #sentence lower
    sentence = sentence.lower()
    #tokenize
    tokens = nltk.word_tokenize(sentence)
    
    text_preprocessed_1.append(' '.join(tokens))

In [8]:
len(text_preprocessed_1),len(text_preprocessed), len(text)

(999, 999, 999)

### Extracting Text and Train Data

In [9]:
from sklearn.model_selection import train_test_split

trainX, testX, trainY, testY = train_test_split(
    text_preprocessed, label, test_size=0.3, random_state=42)


len(trainX), len(testX), len(trainY), len(testY)

(699, 300, 699, 300)

In [66]:
#encode lables (0-ham, 1-spam)
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
trainY= le.fit_transform(trainY)
testY = le.fit_transform(testY)
trainY.shape,testY.shape
trainY[0]

3

In [11]:
np.unique(trainY, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6]), array([ 68, 104,  89, 167,  74, 108,  89]))

In [12]:
trainY

array([3, 5, 1, 3, 5, 4, 5, 0, 0, 3, 5, 5, 3, 5, 1, 2, 4, 3, 2, 6, 2, 4,
       4, 3, 0, 0, 1, 0, 2, 5, 4, 5, 1, 6, 4, 3, 3, 4, 5, 1, 1, 2, 6, 5,
       3, 0, 6, 0, 2, 4, 3, 6, 4, 2, 4, 1, 4, 2, 5, 5, 2, 1, 2, 6, 0, 2,
       3, 5, 2, 1, 2, 2, 6, 0, 3, 6, 3, 1, 2, 2, 3, 2, 2, 5, 3, 2, 0, 1,
       2, 6, 3, 6, 5, 6, 3, 1, 5, 3, 6, 3, 1, 5, 5, 3, 0, 4, 6, 5, 5, 0,
       5, 4, 5, 3, 3, 1, 5, 1, 6, 3, 1, 5, 5, 4, 6, 6, 0, 4, 4, 4, 4, 0,
       4, 6, 2, 4, 1, 0, 2, 3, 0, 1, 5, 5, 3, 2, 5, 5, 5, 5, 1, 2, 2, 5,
       3, 5, 1, 1, 6, 6, 5, 5, 1, 6, 6, 1, 3, 1, 1, 6, 3, 6, 4, 0, 0, 0,
       5, 3, 3, 6, 6, 1, 5, 6, 6, 4, 2, 1, 0, 5, 3, 6, 1, 2, 1, 1, 0, 3,
       5, 2, 1, 3, 3, 0, 3, 1, 0, 5, 4, 5, 4, 5, 6, 4, 3, 2, 2, 0, 6, 4,
       5, 0, 4, 1, 0, 3, 2, 5, 6, 5, 6, 5, 4, 3, 1, 2, 6, 3, 1, 2, 4, 2,
       1, 6, 3, 1, 5, 5, 6, 6, 1, 3, 6, 3, 0, 4, 4, 6, 4, 2, 0, 3, 3, 4,
       1, 3, 4, 4, 0, 2, 6, 3, 6, 4, 0, 2, 1, 1, 3, 4, 6, 3, 3, 3, 1, 5,
       3, 6, 2, 2, 3, 5, 3, 3, 2, 4, 5, 5, 3, 6, 6,

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

# Count Vectors as features
# create a count vectorizer object 
count_vect = CountVectorizer(max_features=5000)
count_vect.fit(text_preprocessed)

# transform the training and test data using count vectorizer object
trainX_vec = count_vect.transform(trainX)
testX_vec = count_vect.transform(testX)
trainX_vec.shape,
testX_vec.shape

(300, 5000)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score


#create an instance of the model
lr_model = LogisticRegression(random_state=7)
#train the model
lr_model.fit(trainX_vec, trainY)

#predict test data
pred_test = lr_model.predict(testX_vec)

#print evaluation metrics 
print(classification_report(testY,pred_test))
print(confusion_matrix(testY,pred_test))
print("Accuracy:", accuracy_score(testY, pred_test))

              precision    recall  f1-score   support

           0       0.86      0.80      0.83        30
           1       0.83      0.87      0.85        39
           2       0.70      0.74      0.72        31
           3       0.83      0.95      0.89        65
           4       0.93      0.87      0.90        46
           5       0.76      0.71      0.73        48
           6       0.89      0.76      0.82        41

    accuracy                           0.83       300
   macro avg       0.83      0.81      0.82       300
weighted avg       0.83      0.83      0.83       300

[[24  1  4  0  0  1  0]
 [ 1 34  0  3  1  0  0]
 [ 1  1 23  1  0  5  0]
 [ 0  2  0 62  0  1  0]
 [ 1  0  0  2 40  0  3]
 [ 1  1  5  5  1 34  1]
 [ 0  2  1  2  1  4 31]]
Accuracy: 0.8266666666666667


### Вториот модел - не процесиран текст

In [15]:
from sklearn.model_selection import train_test_split

trainX_1, testX_1, trainY_1, testY_1 = train_test_split(
    text_preprocessed_1, label, test_size=0.3, random_state=42)


len(trainX), len(testX), len(trainY), len(testY)


len(trainX_1), len(testX_1) ,len(trainY_1), len(testY_1)

(699, 300, 699, 300)

In [16]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
trainY_1= le.fit_transform(trainY_1)
testY_1 = le.fit_transform(testY_1)
trainY_1.shape,testY_1.shape
trainY_1[0]

3

In [17]:
count_vect_1 = CountVectorizer(max_features=5000)
count_vect_1.fit(text_preprocessed_1)

# transform the training and test data using count vectorizer object
trainX_1_vec = count_vect.transform(trainX_1)
testX_1_vec = count_vect.transform(testX_1)
trainX_1_vec.shape,
testX_1_vec.shape

(300, 5000)

In [18]:
lr_model_1 = LogisticRegression(random_state=0)
lr_model_1.fit(trainX_1_vec, trainY_1)

pred_test_1 = lr_model_1.predict(testX_1_vec)

#print evaluation metrics 
print(classification_report(testY_1,pred_test_1))
print(confusion_matrix(testY_1,pred_test_1))
print("Accuracy:",accuracy_score(testY_1, pred_test_1))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80        30
           1       0.72      0.85      0.78        39
           2       0.69      0.71      0.70        31
           3       0.80      0.92      0.86        65
           4       0.81      0.76      0.79        46
           5       0.88      0.73      0.80        48
           6       0.79      0.66      0.72        41

    accuracy                           0.79       300
   macro avg       0.78      0.78      0.78       300
weighted avg       0.79      0.79      0.79       300

[[24  1  3  1  1  0  0]
 [ 1 33  0  0  2  2  1]
 [ 2  2 22  2  1  1  1]
 [ 0  2  1 60  1  1  0]
 [ 1  3  0  2 35  0  5]
 [ 0  2  4  6  1 35  0]
 [ 2  3  2  4  2  1 27]]
Accuracy: 0.7866666666666666


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC


In [20]:
tfidf = TfidfVectorizer(max_features=5000, stop_words={"english"}, ngram_range=(1, 3)) 
tfidf.fit(text)

X_train_tfidf = tfidf.transform(trainX)
X_test_tfidf = tfidf.transform(testX)

X_train_tfidf.shape, X_test_tfidf.shape

((699, 5000), (300, 5000))

In [21]:
lr_model_tf = LogisticRegression(random_state=0)
lr_model_tf.fit(X_train_tfidf, trainY)
pred_test_tf = lr_model_tf.predict(X_test_tfidf)

#print evaluation metrics 
print(classification_report(testY,pred_test_tf))
print(confusion_matrix(testY,pred_test_tf))
print("Accuracy:",accuracy_score(testY, pred_test_tf))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67        30
           1       0.73      0.90      0.80        39
           2       0.82      0.74      0.78        31
           3       0.72      0.97      0.83        65
           4       0.95      0.85      0.90        46
           5       0.89      0.83      0.86        48
           6       0.81      0.71      0.75        41

    accuracy                           0.81       300
   macro avg       0.85      0.79      0.80       300
weighted avg       0.83      0.81      0.81       300

[[15  4  2  7  0  2  0]
 [ 0 35  0  1  1  0  2]
 [ 0  2 23  3  0  2  1]
 [ 0  1  0 63  0  0  1]
 [ 0  2  0  2 39  0  3]
 [ 0  0  3  5  0 40  0]
 [ 0  4  0  6  1  1 29]]
Accuracy: 0.8133333333333334


In [22]:
lr_model_tf = LogisticRegression(random_state=0)
lr_model_tf.fit(X_train_tfidf, trainY)
pred_test_tf = lr_model_tf.predict(X_test_tfidf)

#print evaluation metrics 
print(classification_report(testY,pred_test_tf))
print(confusion_matrix(testY,pred_test_tf))
print("Accuracy:",accuracy_score(testY, pred_test_tf))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67        30
           1       0.73      0.90      0.80        39
           2       0.82      0.74      0.78        31
           3       0.72      0.97      0.83        65
           4       0.95      0.85      0.90        46
           5       0.89      0.83      0.86        48
           6       0.81      0.71      0.75        41

    accuracy                           0.81       300
   macro avg       0.85      0.79      0.80       300
weighted avg       0.83      0.81      0.81       300

[[15  4  2  7  0  2  0]
 [ 0 35  0  1  1  0  2]
 [ 0  2 23  3  0  2  1]
 [ 0  1  0 63  0  0  1]
 [ 0  2  0  2 39  0  3]
 [ 0  0  3  5  0 40  0]
 [ 0  4  0  6  1  1 29]]
Accuracy: 0.8133333333333334


In [23]:
#Language processing
from nltk.text import Text
text_class = Text(text)
text_class.concordance("crime") # - колку пати се појавува зборот


No matches


In [24]:
words= nltk.word_tokenize(text[2])
length= len(words) 
print(length) 
print(text[2]) 

99
Now she had got a start, and she went on and told me all about the good
place. She said all a body would have to do there was to go around all
day long with a harp and sing, forever and ever. So I didn't think
much of it. But I never said so. I asked her if she reckoned Tom Sawyer
would go there, and she said not by a considerable sight. I was glad
about that, because I wanted him and me to be together.


In [25]:
paragraph = text[25]
sentences = nltk.sent_tokenize(paragraph) 
length= len(sentences) 
print(text[25]) 
print(length) 

“Yo' ole father doan' know yit what he's a-gwyne to do. Sometimes he
spec he'll go 'way, en den agin he spec he'll stay. De bes' way is to
res' easy en let de ole man take his own way. Dey's two angels hoverin'
roun' 'bout him. One uv 'em is white en shiny, en t'other one is black.
De white one gits him to go right a little while, den de black one sail
in en bust it all up. A body can't tell yit which one gwyne to fetch
him at de las'. But you is all right. You gwyne to have considable
trouble in yo' life, en considable joy. Sometimes you gwyne to git
hurt, en sometimes you gwyne to git sick; but every time you's gwyne
to git well agin. Dey's two gals flyin' 'bout you in yo' life. One
uv 'em's light en t'other one is dark. One is rich en t'other is po'.
You's gwyne to marry de po' one fust en de rich one by en by. You
wants to keep 'way fum de water as much as you kin, en don't run no
resk, 'kase it's down in de bills dat you's gwyne to git hung.”
15


In [26]:
# mutlinomial NB, Random Forest, SVM(kernel='linear', probability=True) bi gi probala


In [27]:
# # embeddings 
# from gensim.models.word2vec import Word2Vec
# from gensim.models import Phrases

# bigramer = Phrases(sentences)
# model = Word2Vec(bigramer[sentences], window=5, min_count=10, workers=4)

# # unload memory
# model.init_sims(replace=True) 

# # Storing a model
# model.save("author")
# # new_model = gensim.models.Word2Vec.load('author')

# # Switch to KeyedVectors instance  
# # w2v = {w: vec for w,vec in text_preprocessed}

In [28]:
# model.most_similar()

In [29]:
class EmbeddingVectorizer(object):
    # If word2vec were passed in during initialization, use those
    def __init__(self, word2vec):
        self.word2vec = word2vec
        self.word2weight = None
        self.dim = 100
    
    # learning word2weight
    def fit(self, X, y):
        vect = TfidfVectorizer(min_df=5, ngram_range=(1,3))
        vect.fit(X)
        max_idf = max(vect.idf_)
        self.word2weight = defaultdict(
        lambda: max_idf, [(w, vect.idf_[i]) for w, i in vect.vocabulary_.items()]
        )
        return self
    
    # Use learned word2weight
    def transform(self, X):
        return np.array([
            np.mean([
                self.word2vec[w]*self.word2weight[w] 
                for w in words if w in self.word2vec] or 
                [np.zeros(self.dim)], axis=0) 
            for words in X
        ])
        

In [30]:
from keras.preprocessing.text import Tokenizer #similar to the CountVectorizer and TfIDF from sci-kit

#The word embedding layer expects input sequences to be comprised of integers.
# integer encode sequences of words
tokenizer = Tokenizer()

tokenizer.fit_on_texts(text_preprocessed)

sequences = tokenizer.texts_to_sequences(text_preprocessed)

In [31]:
tokenizer.word_index

{'’': 1,
 '“': 2,
 '”': 3,
 'say': 4,
 'would': 5,
 'one': 6,
 'go': 7,
 'mr': 8,
 'make': 9,
 'man': 10,
 'could': 11,
 'like': 12,
 'come': 13,
 'take': 14,
 'time': 15,
 'get': 16,
 'see': 17,
 'upon': 18,
 'little': 19,
 'know': 20,
 'look': 21,
 'well': 22,
 'great': 23,
 'hand': 24,
 'good': 25,
 'give': 26,
 'much': 27,
 'thing': 28,
 'seem': 29,
 'way': 30,
 'old': 31,
 '‘': 32,
 'might': 33,
 'day': 34,
 'never': 35,
 'even': 36,
 'two': 37,
 'every': 38,
 'eye': 39,
 'men': 40,
 'turn': 41,
 'life': 42,
 'head': 43,
 'thought': 44,
 'house': 45,
 'sir': 46,
 'back': 47,
 'young': 48,
 'people': 49,
 'woman': 50,
 'first': 51,
 'work': 52,
 'tom': 53,
 'must': 54,
 'think': 55,
 'may': 56,
 'mind': 57,
 'always': 58,
 'many': 59,
 'call': 60,
 'face': 61,
 'saw': 62,
 'away': 63,
 'long': 64,
 'though': 65,
 'u': 66,
 'last': 67,
 'year': 68,
 'without': 69,
 'want': 70,
 'nothing': 71,
 'ever': 72,
 'casaubon': 73,
 'boy': 74,
 'night': 75,
 'put': 76,
 'place': 77,
 'world':

In [49]:
sequences = np.array(sequences)

trainX, testX, trainY, testY = train_test_split(
    sequences, label, test_size=0.3, random_state=42)
trainX = np.array(trainX)
testX = np.array(testX)
trainY = np.array(trainY)
testY = np.array(testY)


len(trainX), len(testX), len(trainY), len(testY)

# trainX.shape, testX.shape, trainY.shape, testY.shape

(699, 300, 699, 300)

In [50]:
from keras.preprocessing.sequence import pad_sequences

max_len = 100
#transforms a list (of length num_samples) of sequences (lists of integers) 
#into a 2D Numpy array of shape (num_samples, num_timesteps) num_timesteps is the maxlen argument.

train_X_pad = pad_sequences(trainX, maxlen = max_len, dtype='int32')
test_X_pad = pad_sequences(testX, maxlen = max_len, dtype='int32')

print(train_X_pad.shape)
print(test_X_pad.shape)

(699, 100)
(300, 100)


In [51]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size
#tokenizer.word_index

11996

In [68]:
# create the model
from keras.models import Model
from keras.layers import Input, Embedding, LSTM, Dense

def generate_model(vocab_size, max_len, embedding_size):

    _input = Input(max_len)

    x = Embedding(input_dim = vocab_size, output_dim = embedding_size) (_input)

    x = LSTM(50)(x)

    output = Dense(7, activation='softmax')(x)

    model = Model(inputs= [_input], outputs = [output])

    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [74]:
#trainY
#dropout sloj posle LSTM, moze da se smeni embedding size

In [90]:
model = generate_model(vocab_size , max_len , embedding_size=80)
model.summary()

Model: "model_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_10 (InputLayer)       [(None, 100)]             0         
                                                                 
 embedding_9 (Embedding)     (None, 100, 80)           959680    
                                                                 
 lstm_9 (LSTM)               (None, 50)                26200     
                                                                 
 dense_9 (Dense)             (None, 7)                 357       
                                                                 
Total params: 986,237
Trainable params: 986,237
Non-trainable params: 0
_________________________________________________________________


In [91]:
trainX= np.array(trainX)
trainY= np.array(trainY)

In [92]:
history = model.fit(train_X_pad, trainY, epochs=10, batch_size=60, validation_data=(test_X_pad, testY))

Epoch 1/10
12/12 [==============================] - 4s 144ms/step - loss: 1.9392 - accuracy: 0.1946 - val_loss: 1.9322 - val_accuracy: 0.2167
Epoch 2/10
12/12 [==============================] - 1s 92ms/step - loss: 1.8902 - accuracy: 0.2389 - val_loss: 1.8975 - val_accuracy: 0.2167
Epoch 3/10
12/12 [==============================] - 1s 91ms/step - loss: 1.8097 - accuracy: 0.2418 - val_loss: 1.8608 - val_accuracy: 0.2267
Epoch 4/10
12/12 [==============================] - 1s 91ms/step - loss: 1.6176 - accuracy: 0.2647 - val_loss: 1.7171 - val_accuracy: 0.2367
Epoch 5/10
12/12 [==============================] - 1s 92ms/step - loss: 1.3041 - accuracy: 0.6767 - val_loss: 1.6057 - val_accuracy: 0.3833
Epoch 6/10
12/12 [==============================] - 1s 92ms/step - loss: 1.0475 - accuracy: 0.7897 - val_loss: 1.3873 - val_accuracy: 0.4867
Epoch 7/10
12/12 [==============================] - 1s 91ms/step - loss: 0.8296 - accuracy: 0.8298 - val_loss: 1.4004 - val_accuracy: 0.4800
Epoch 8/10
1

In [93]:
pred_test = model.predict(test_X_pad)
pred_test = np.argmax(pred_test,axis=1)
#pred_test = pred_test.round()

#print evaluation metrics 
print(classification_report(testY,pred_test))
print(confusion_matrix(testY,pred_test))
print("Accuracy:",accuracy_score(testY, pred_test))

              precision    recall  f1-score   support

           0       0.50      0.10      0.17        30
           1       0.50      0.56      0.53        39
           2       0.48      0.74      0.58        31
           3       0.77      0.82      0.79        65
           4       0.66      0.85      0.74        46
           5       0.59      0.62      0.61        48
           6       0.57      0.32      0.41        41

    accuracy                           0.61       300
   macro avg       0.58      0.57      0.55       300
weighted avg       0.60      0.61      0.58       300

[[ 3  1 16  1  4  5  0]
 [ 0 22  0  3  4  2  8]
 [ 0  0 23  1  2  5  0]
 [ 0  4  2 53  0  6  0]
 [ 0  2  0  3 39  0  2]
 [ 3  1  7  6  1 30  0]
 [ 0 14  0  2  9  3 13]]
Accuracy: 0.61
